name: Ansible build actions
on:
  workflow_dispatch: 
jobs:

  build:
    name: Project Build
    runs-on: ubuntu-latest
    steps:
    - name: Remote Script
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
